import math
import multiprocessing

from hipop.graph import OrientedGraph
from hipop.shortest_path import dijkstra, parallel_dijkstra


# Graph similar to the one generated by function simple_graph() in cpp/tests/sample_graphs.h,
# with no bus layer:
#
# ```
#         5           1.5
#   A --------> B --------> C
#   |           |           |
#  6|           |4          |4
#   |           |           |
#   v           v           v
#   D --------> E --------> F
#        2            3
#
#               I (isolated node)
# ```
def _make_simple_graph() -> OrientedGraph:

    G = OrientedGraph()

    G.add_node("A", 0, 0, "")
    G.add_node("B", 1, 0, "")
    G.add_node("C", 2, 0, "")
    G.add_node("D", 0, 1, "")
    G.add_node("E", 1, 1, "")
    G.add_node("F", 2, 1, "")
    G.add_node("I", 2, 2, "")

    G.add_link("A_B", "A", "B", 1, {"CAR": {"time": 5}}, "CarLayer")
    G.add_link("B_C", "B", "C", 1, {"CAR": {"time": 1.5}}, "CarLayer")
    G.add_link("D_E", "D", "E", 1, {"CAR": {"time": 2}}, "CarLayer")
    G.add_link("E_F", "E", "F", 1, {"CAR": {"time": 3}}, "CarLayer")
    G.add_link("A_D", "A", "D", 1, {"CAR": {"time": 6}}, "CarLayer")
    G.add_link("B_E", "B", "E", 1, {"CAR": {"time": 4}}, "CarLayer")
    G.add_link("C_F", "C", "F", 1, {"CAR": {"time": 4}}, "CarLayer")

    return G


# Test the shortest_path bindings (non-parallel case).
# REMARK: here, the goal is to validate the bindings, not to cover
# all the algorithmic edge cases (these are covered in the C++ tests).
def test_dijkstra() -> None:

    G = _make_simple_graph()

    # Standard cases
    path = dijkstra(G, "A", "E", "time", {"CarLayer": "CAR"})
    assert path == (["A", "D", "E"], 8), "A -> E"
    path = dijkstra(G, "B", "F", "time", {"CarLayer": "CAR"})
    assert path == (["B", "C", "F"], 5.5), "B -> F"
    path = dijkstra(G, "A", "F", "time", {"CarLayer": "CAR"})
    assert path == (["A", "B", "C", "F"], 10.5), "A -> F"

    # Edge cases
    path = dijkstra(G, "A", "A", "time", {"CarLayer": "CAR"})
    assert path == ([], 0), "Empty path A -> A"
    path = dijkstra(G, "B", "B", "time", {"CarLayer": "CAR"})
    assert path == ([], 0), "Empty path B -> B"
    path = dijkstra(G, "A", "I", "time", {"CarLayer": "CAR"})
    assert path == ([], math.inf), "Non-feasible path A -> I"
    path = dijkstra(G, "D", "A", "time", {"CarLayer": "CAR"})
    assert path == ([], math.inf), "Non-feasible path D -> A"


# Test the shortest_path bindings (parallel case, involving OpenMP).
def test_parallel_dijkstra() -> None:

    G = _make_simple_graph()

    origins      = ["A", "B", "A", "A", "B", "A", "D"]
    destinations = ["E", "F", "F", "A", "B", "I", "A"]
    paths = parallel_dijkstra(G, origins, destinations, [{"CarLayer": "CAR"}] * len(origins), "time", multiprocessing.cpu_count())

    assert paths == [
        # Standard cases
        (["A", "D", "E"], 8),
        (["B", "C", "F"], 5.5),
        (["A", "B", "C", "F"], 10.5),
        # Edge cases
        ([], 0),
        ([], 0),
        ([], math.inf),
        ([], math.inf),
    ]
